scenario:
  distance:
  - DKIENL
  - DEDKIE
  - DKIELV
  - DKGRIE
  - DKIEPT
  - DKFRIE
  - DEDKNL
  - DKLVNL
  - DKGRNL
  - DKNLPT
  - DKFRNL
  - DEDKLV
  - DEDKGR
  - DEDKPT
  - DEDKFR
  - DKGRLV
  - DKLVPT
  - DKFRLV
  - DKGRPT
  - DKFRGR
  - DKFRPT
  - DEIENL
  - IELVNL
  - GRIENL
  - IENLPT
  - FRIENL
  - DEIELV
  - DEGRIE
  - DEIEPT
  - DEFRIE
  - GRIELV
  - IELVPT
  - FRIELV
  - GRIEPT
  - FRGRIE
  - FRIEPT
  - DELVNL
  - DEGRNL
  - DENLPT
  - DEFRNL
  - GRLVNL
  - LVNLPT
  - FRLVNL
  - GRNLPT
  - FRGRNL
  - FRNLPT
  - DEGRLV
  - DELVPT
  - DEFRLV
  - DEGRPT
  - DEFRGR
  - DEFRPT
  - GRLVPT
  - FRGRLV
  - FRLVPT
  - FRGRPT
ci:
  DKIENL:
    datacenters:
      DK1 0: Denmark
      IE5 0: Ireland
      NL1 0: Netherlands
  DEDKIE:
    datacenters:
      DK1 0: Denmark
      IE5 0: Ireland
      DE1 0: Germany
  DKIELV:
    datacenters:
      DK1 0: Denmark
      IE5 0: Ireland
      LV6 0: Latvia
  DKGRIE:
    datacenters:
      DK1 0: Denmark
      IE5 0: Ireland
      GR1 0: Greece
  DKIEPT:
    datacenters:
      DK1 0: Denmark
      IE5 0: Ireland
      PT1 0: Portugal
  DKFRIE:
    datacenters:
      DK1 0: Denmark
      IE5 0: Ireland
      FR1 0: France
  DEDKNL:
    datacenters:
      DK1 0: Denmark
      NL1 0: Netherlands
      DE1 0: Germany
  DKLVNL:
    datacenters:
      DK1 0: Denmark
      NL1 0: Netherlands
      LV6 0: Latvia
  DKGRNL:
    datacenters:
      DK1 0: Denmark
      NL1 0: Netherlands
      GR1 0: Greece
  DKNLPT:
    datacenters:
      DK1 0: Denmark
      NL1 0: Netherlands
      PT1 0: Portugal
  DKFRNL:
    datacenters:
      DK1 0: Denmark
      NL1 0: Netherlands
      FR1 0: France
  DEDKLV:
    datacenters:
      DK1 0: Denmark
      DE1 0: Germany
      LV6 0: Latvia
  DEDKGR:
    datacenters:
      DK1 0: Denmark
      DE1 0: Germany
      GR1 0: Greece
  DEDKPT:
    datacenters:
      DK1 0: Denmark
      DE1 0: Germany
      PT1 0: Portugal
  DEDKFR:
    datacenters:
      DK1 0: Denmark
      DE1 0: Germany
      FR1 0: France
  DKGRLV:
    datacenters:
      DK1 0: Denmark
      LV6 0: Latvia
      GR1 0: Greece
  DKLVPT:
    datacenters:
      DK1 0: Denmark
      LV6 0: Latvia
      PT1 0: Portugal
  DKFRLV:
    datacenters:
      DK1 0: Denmark
      LV6 0: Latvia
      FR1 0: France
  DKGRPT:
    datacenters:
      DK1 0: Denmark
      GR1 0: Greece
      PT1 0: Portugal
  DKFRGR:
    datacenters:
      DK1 0: Denmark
      GR1 0: Greece
      FR1 0: France
  DKFRPT:
    datacenters:
      DK1 0: Denmark
      PT1 0: Portugal
      FR1 0: France
  DEIENL:
    datacenters:
      IE5 0: Ireland
      NL1 0: Netherlands
      DE1 0: Germany
  IELVNL:
    datacenters:
      IE5 0: Ireland
      NL1 0: Netherlands
      LV6 0: Latvia
  GRIENL:
    datacenters:
      IE5 0: Ireland
      NL1 0: Netherlands
      GR1 0: Greece
  IENLPT:
    datacenters:
      IE5 0: Ireland
      NL1 0: Netherlands
      PT1 0: Portugal
  FRIENL:
    datacenters:
      IE5 0: Ireland
      NL1 0: Netherlands
      FR1 0: France
  DEIELV:
    datacenters:
      IE5 0: Ireland
      DE1 0: Germany
      LV6 0: Latvia
  DEGRIE:
    datacenters:
      IE5 0: Ireland
      DE1 0: Germany
      GR1 0: Greece
  DEIEPT:
    datacenters:
      IE5 0: Ireland
      DE1 0: Germany
      PT1 0: Portugal
  DEFRIE:
    datacenters:
      IE5 0: Ireland
      DE1 0: Germany
      FR1 0: France
  GRIELV:
    datacenters:
      IE5 0: Ireland
      LV6 0: Latvia
      GR1 0: Greece
  IELVPT:
    datacenters:
      IE5 0: Ireland
      LV6 0: Latvia
      PT1 0: Portugal
  FRIELV:
    datacenters:
      IE5 0: Ireland
      LV6 0: Latvia
      FR1 0: France
  GRIEPT:
    datacenters:
      IE5 0: Ireland
      GR1 0: Greece
      PT1 0: Portugal
  FRGRIE:
    datacenters:
      IE5 0: Ireland
      GR1 0: Greece
      FR1 0: France
  FRIEPT:
    datacenters:
      IE5 0: Ireland
      PT1 0: Portugal
      FR1 0: France
  DELVNL:
    datacenters:
      NL1 0: Netherlands
      DE1 0: Germany
      LV6 0: Latvia
  DEGRNL:
    datacenters:
      NL1 0: Netherlands
      DE1 0: Germany
      GR1 0: Greece
  DENLPT:
    datacenters:
      NL1 0: Netherlands
      DE1 0: Germany
      PT1 0: Portugal
  DEFRNL:
    datacenters:
      NL1 0: Netherlands
      DE1 0: Germany
      FR1 0: France
  GRLVNL:
    datacenters:
      NL1 0: Netherlands
      LV6 0: Latvia
      GR1 0: Greece
  LVNLPT:
    datacenters:
      NL1 0: Netherlands
      LV6 0: Latvia
      PT1 0: Portugal
  FRLVNL:
    datacenters:
      NL1 0: Netherlands
      LV6 0: Latvia
      FR1 0: France
  GRNLPT:
    datacenters:
      NL1 0: Netherlands
      GR1 0: Greece
      PT1 0: Portugal
  FRGRNL:
    datacenters:
      NL1 0: Netherlands
      GR1 0: Greece
      FR1 0: France
  FRNLPT:
    datacenters:
      NL1 0: Netherlands
      PT1 0: Portugal
      FR1 0: France
  DEGRLV:
    datacenters:
      DE1 0: Germany
      LV6 0: Latvia
      GR1 0: Greece
  DELVPT:
    datacenters:
      DE1 0: Germany
      LV6 0: Latvia
      PT1 0: Portugal
  DEFRLV:
    datacenters:
      DE1 0: Germany
      LV6 0: Latvia
      FR1 0: France
  DEGRPT:
    datacenters:
      DE1 0: Germany
      GR1 0: Greece
      PT1 0: Portugal
  DEFRGR:
    datacenters:
      DE1 0: Germany
      GR1 0: Greece
      FR1 0: France
  DEFRPT:
    datacenters:
      DE1 0: Germany
      PT1 0: Portugal
      FR1 0: France
  GRLVPT:
    datacenters:
      LV6 0: Latvia
      GR1 0: Greece
      PT1 0: Portugal
  FRGRLV:
    datacenters:
      LV6 0: Latvia
      GR1 0: Greece
      FR1 0: France
  FRLVPT:
    datacenters:
      LV6 0: Latvia
      PT1 0: Portugal
      FR1 0: France
  FRGRPT:
    datacenters:
      GR1 0: Greece
      PT1 0: Portugal
      FR1 0: France
